### ISSUE TITLE
APPLICATION metadata block: riff (BWF), aiff and w64

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/flac-specification#103]
The FLAC format has room for application specific data, which may or may not have an open specification. I haven't heard of widespread use of any of them and I'd say most of them are of no value to cellar.

There are however three of these that are used by the `flac` command line utility that store RIFF (WAVE), AIFF and W64 metadata. As the cellar wg is specifically targeting archival usage, are the metadata capabilities of WAVE and AIFF used to some extent in archival applications? Would it be of any use to include a definition of these riff, aiff and w64 application metadata blocks, despite not technically being part of the FLAC specification?

edit: or perhaps such metadata would (from a cellar perspective) be better stored directly in the Matroska metadata?

**Comment by retokromer** [comment]
I personally would prefer having them (I am thinking _in primis_ of RIFF) with the codec rather than with the container.

**Comment by JeromeMartinez** [comment]
> I haven't heard of widespread use of any of them and I'd say most of them are of no value to cellar.

Well, for video we had to create a dedicated format for that, [RAWcooked](https://mediaarea.net/RAWcooked), because there is no format with this feature. Well... We actually also implemented it for audio in FLAC, because we call FFmpeg which does not handle that AFAIK + we had to implement it for raw PCM.

> Would it be of any use to include a definition of these riff, aiff and w64 application metadata blocks, despite not technically being part of the FLAC specification?

As for Matroska, there is a core spec (I am OK for including audio channel layout because it is relevant for the decoder for assigning the right channels :) ) and there is a tag spec, here the core spec refers to https://xiph.org/flac/id.html so IMHO it is fine enough for at least the core document.

**Comment by JeromeMartinez** [comment]
I mean that it has a certain value.
But:

> perhaps I should write out the current implementation and submit it for inclusion on the FLAC website so it can be linked from this specification?

IMHO it is not the core of the format, and at the difference of the WAVEFORMATEXTENSIBLE_CHANNEL_MASK such things don't have a role of expanding a limited list in the core of the format (it is for very specific purposes) so it would worth it to document it, definitely, but maybe not in the main document which will be sent to IETF (the ID list and the corresponding list would be hosted in this repo but in a separate document).
