### ISSUE TITLE
Document what is allowed to change between frames

### ISSUE THREAD

**Issue by wader** [ietf-wg-cellar/flac-specification#109]
For example can one assume that for a valid FLAC stream sample rate, channel configuration and channel count must be the same for all frames and also must match what is specified in streaminfo?

**Comment by JeromeMartinez** [comment]
In practice we have tons of issues there :), because it looks like the format was built with linear compression and no cut in mind (= write once, never remux) and AFAIK tools which do a cut don't change the CODED NUMBER and don't check for compatibility if STREAMINFO is same but BLOCKING STRATEGY is not (they just concatenate).
And actually it seems to not be a problem for most decoders (ignoring the CODED NUMBER?).

Usage goes farer than spec, so it is spec (and flac command tool) vs practice, I think we should document practice there (CODED NUMBER to be ignored? using "MAY" wording?). And put all about a "perfect stream" in the "Subset" or somewhere about the difference between a "native" encoding and a remux/cut/streaming.

**Comment by ktmf01** [comment]
What about adding this to the section dissecting the frame header

> Each frame header stores the audio sample rate, number of bits per sample and number of channels independently of other frame headers. This was done to simplify streaming of FLAC files over the internet (for example in internet radio) but it also allows these properties to change mid-stream. Because not all environments in which FLAC decoders are used are able to cope with changes to these parameters during playback, a decoder MAY choose to stop decoding on such a change. A decoder that does not check for such a change could be vulnerable to buffer overflows. See also [the section on security considerations](#security-considerations).

And this to the coded number section

> In case the coded number is a frame number, it MUST be equal to the number of frames preceding the current frame. In case the coded number is a sample number, it MUST be equal to the number of samples preceding the current frame. In a stream where these requirements are not met, seeking is not (reliably) possible.
>
> A decoder that relies on the coded number during seeking could be vulnerable to buffer overflows or seeking could get stuck in an infinite loops in case it seeks in a stream where the coded numbers are non-consecutive or otherwise invalid. See also [the section on security considerations](#security-considerations).
