### ISSUE TITLE
Normative references

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/flac-specification#225]
From https://mailarchive.ietf.org/arch/msg/cellar/1hKWAbLAq9UrmV1Mb25QkM0j3Ug/

> > I think IEC.60908.1999 should be a normative reference.  I think the references to RFC 6838 and RFC 7942 should be normative, but I also don't think they are necessary and could be removed to simplify things a bit.
>
> Please explain. I thought normative references specify documents that must be read to understand or implement this document? How can the reference be a required read only when present?
>
> As for IEC.60908.1999, could you please explain what parts of the specification are hard to understand without having read it? I don't have access to IEC.60908.1999, I have never read it myself, and as far as I know all relevant parts have already been explained in this document. From my point of view, the reference is only there to point to the origin of some fields.

So, which references should be normative and why?

**Comment by mcr** [comment]
The IEC document is annoying because they want money for it.  It makes it hard for reviewers.  So that's the first question.  Can it be informative, or do we need it at all?  I think that the Cuesheet is fully specified?  If so, we can write:

   Certain aspects of this metadata block follow directly from the CD-DA specification, called Red Book, which is standardized as [IEC.60908.1999].  The description below is complete and further reference to [IEC.60908.1999] is not needed to implement this metadata block.

I don't thin RFC6838 needs to be normative, since we read them and them filed the media-type registration.
Ditto 7942.

**Comment by ktmf01** [comment]
Yes, the IEC document isn't needed (I don't have it either). Thanks for the suggestion, I'll add that.
